import { createVectorDBService } from '$lib/services/vector-db';
const main = async () => {                                                                                                                                                                                                                                                 
    const databaseUrl = process.env.VECTOR_DATABASE_URL;                                                                                                                                                                                                                     
    const cohereApiKey = process.env.COHERE_API_KEY;                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                             
    if (!databaseUrl || !cohereApiKey) {                                                                                                                                                                                                                                     
      console.error('Missing required environment variables:');                                                                                                                                                                                                              
      if (!databaseUrl) console.error('  - VECTOR_DATABASE_URL');                                                                                                                                                                                                            
      if (!cohereApiKey) console.error('  - COHERE_API_KEY');                                                                                                                                                                                                                
      process.exit(1);                                                                                                                                                                                                                                                       
    }                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                             
    const vectorDB = createVectorDBService(databaseUrl, cohereApiKey);                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                             
    try {                                                                                                                                                                                                                                                                    
      await vectorDB.initialize();                                                                                                                                                                                                                                           
      console.log('✓ Migration completed successfully');                                                                                                                                                                                                                     
      await vectorDB.close();                                                                                                                                                                                                                                                
      process.exit(0);                                                                                                                                                                                                                                                       
    } catch (error: any) {                                                                                                                                                                                                                                                   
      console.error('✗ Migration failed:', error.message);                                                                                                                                                                                                                   
      await vectorDB.close();                                                                                                                                                                                                                                                
      process.exit(1);                                                                                                                                                                                                                                                       
    }                                                                                                                                                                                                                                                                        
  };                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                             
  main();               